using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Hung.Base;
using UnityEditor;

namespace Hung.Data.Editor
{
    public static class ItemIdCodeGenerator
    {
        public static string GenerateContent(IEnumerable<ItemDefinition> definitions, string className = "GameItemIds")
        {
            ItemDefinition[] source = definitions?.ToArray() ?? Array.Empty<ItemDefinition>();
            ItemCatalogValidator.ValidateForCodeGeneration(source);

            List<ItemDefinition> gameDefinitions = source
                .Where(definition => !definition.Id.Value.StartsWith("base.", StringComparison.Ordinal))
                .OrderBy(definition => definition.Id.Value, StringComparer.Ordinal)
                .ToList();

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using Hung.Base;");
            builder.AppendLine();
            builder.AppendLine($"public static class {className}");
            builder.AppendLine("{");

            foreach (ItemDefinition definition in gameDefinitions)
            {
                builder.AppendLine(
                    $"    public static readonly ItemId {definition.CodeName} = new(\"{definition.Id.Value}\");");
            }

            builder.AppendLine("}");
            return builder.ToString().Replace("\r\n", "\n");
        }

        public static bool WriteIfChanged(string path, string content)
        {
            content = content.Replace("\r\n", "\n");
            if (File.Exists(path) && File.ReadAllText(path).Replace("\r\n", "\n") == content)
                return false;

            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, content);
            AssetDatabase.ImportAsset(ToAssetPath(path));
            return true;
        }

        private static string ToAssetPath(string path)
        {
            string normalized = path.Replace("\\", "/");
            string project = Directory.GetCurrentDirectory().Replace("\\", "/") + "/";
            return normalized.StartsWith(project, StringComparison.Ordinal)
                ? normalized.Substring(project.Length)
                : normalized;
        }
    }
}
