# Generates .cursor/memory/mem-asmdef-matrix.md from Assets/**/*.asmdef.
# Only assemblies listed in asmdef-layers.json appear as rows; references to
# unlisted (third-party) assemblies are shown but not layer-checked.
param(
    [string]$ProjectRoot = (Get-Location).Path,
    [string]$LayerMapPath = ".claude/tools/asmdef-layers.json",
    [string]$OutPath = ".cursor/memory/mem-asmdef-matrix.md"
)
$ErrorActionPreference = 'Stop'
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$layerMap = @{}
$lmFile = Join-Path $ProjectRoot $LayerMapPath
$lmJson = ConvertFrom-Json ([System.IO.File]::ReadAllText($lmFile))
foreach ($p in $lmJson.PSObject.Properties) { $layerMap[$p.Name] = [int]$p.Value }

$asmdefs = Get-ChildItem -Path (Join-Path $ProjectRoot 'Assets') -Recurse -Filter *.asmdef

# GUID -> assembly name map (asmdef references may use GUID form)
$guidToName = @{}
foreach ($f in $asmdefs) {
    $meta = "$($f.FullName).meta"
    if (Test-Path $meta) {
        $m = Select-String -Path $meta -Pattern '^guid:\s*([0-9a-fA-F]+)' | Select-Object -First 1
        if ($m) {
            $name = (ConvertFrom-Json ([System.IO.File]::ReadAllText($f.FullName))).name
            $guidToName[$m.Matches[0].Groups[1].Value] = $name
        }
    }
}

$rows = @()
foreach ($f in $asmdefs) {
    $d = ConvertFrom-Json ([System.IO.File]::ReadAllText($f.FullName))
    if (-not $layerMap.ContainsKey($d.name)) { continue }
    $layer = $layerMap[$d.name]
    $refs = @()
    foreach ($r in @($d.references)) {
        if (-not $r) { continue }
        $rn = $r
        if ($r -match '^(?i)GUID:(.+)$') {
            $g = $Matches[1]
            if ($guidToName.ContainsKey($g)) { $rn = $guidToName[$g] }
        }
        $refs += $rn
    }
    $viol = @()
    foreach ($rn in $refs) {
        if ($layerMap.ContainsKey($rn) -and $layerMap[$rn] -gt $layer) {
            $viol += ("{0} is L{1}" -f $rn, $layerMap[$rn])
        }
    }
    $rows += [pscustomobject]@{
        Name = $d.name; Layer = $layer
        Refs = ($refs -join ', '); Viol = ($viol -join ', ')
    }
}
$rows = $rows | Sort-Object Layer, Name

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# Memory: Asmdef Reference Matrix (Generated)')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('**ID:** `mem-asmdef-matrix` — Ground truth of game assembly references. Read the owning row before introducing any cross-assembly type. A type is only visible if its assembly appears in the References column.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine("> GENERATED by ``.claude/tools/gen-asmdef-matrix.ps1`` on $(Get-Date -Format 'yyyy-MM-dd'). Do NOT hand-edit. Regenerate after any asmdef change (Unity must be open / have regenerated first, per unity-ide-sync rule).")
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| Assembly | Layer | References | Violations (refs pointing to a HIGHER layer) |')
[void]$sb.AppendLine('|---|---|---|---|')
foreach ($r in $rows) {
    $v = if ($r.Viol) { "**$($r.Viol)**" } else { '-' }
    [void]$sb.AppendLine("| ``$($r.Name)`` | $($r.Layer) | $($r.Refs) | $v |")
}
[void]$sb.AppendLine('')
[void]$sb.AppendLine('Violations are tracked debt — see `mem-arch-assemblies-roadmap.md`. New violations must not be introduced.')

$outFile = Join-Path $ProjectRoot $OutPath
[System.IO.File]::WriteAllText($outFile, $sb.ToString(), $Utf8NoBom)
Write-Host "Wrote $OutPath with $($rows.Count) assemblies."
