using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using Hung.Base;
using Hung.Data;
using Hung.Data.Editor;
using NUnit.Framework;

namespace Hung.Data.Editor.Tests
{
    public class ItemCodeGeneratorTests
    {
        [Test]
        public void GenerateContent_SortsGameIdsAndSkipsBaseNamespace()
        {
            string content = ItemIdCodeGenerator.GenerateContent(new[]
            {
                Definition("pet_vs_monster.gem", "Gem"),
                Definition("base.gold", "Gold"),
                Definition("pet_vs_monster.feather", "Feather"),
            });

            const string expected =
                "// <auto-generated />\n" +
                "using Hung.Base;\n" +
                "\n" +
                "public static class GameItemIds\n" +
                "{\n" +
                "    public static readonly ItemId Feather = new(\"pet_vs_monster.feather\");\n" +
                "    public static readonly ItemId Gem = new(\"pet_vs_monster.gem\");\n" +
                "}\n";

            Assert.AreEqual(expected, content);
        }

        [TestCase("1Gem")]
        [TestCase("Gem Name")]
        [TestCase("Gem-Name")]
        public void GenerateContent_InvalidCodeName_Throws(string codeName)
        {
            InvalidOperationException exception = Assert.Throws<InvalidOperationException>(() =>
                ItemIdCodeGenerator.GenerateContent(new[] { Definition("pet_vs_monster.gem", codeName) }));

            StringAssert.Contains(codeName, exception.Message);
        }

        [Test]
        public void GenerateContent_DuplicateCodeName_Throws()
        {
            InvalidOperationException exception = Assert.Throws<InvalidOperationException>(() =>
                ItemIdCodeGenerator.GenerateContent(new[]
                {
                    Definition("pet_vs_monster.gem", "Gem"),
                    Definition("pet_vs_monster.gem_pack", "Gem"),
                }));

            StringAssert.Contains("Gem", exception.Message);
        }

        [Test]
        public void GenerateContent_TestOnlyAcceptanceItem_GeneratesConstant()
        {
            string content = ItemIdCodeGenerator.GenerateContent(new[]
            {
                Definition("pet_vs_monster.item_id_acceptance", "ItemIdAcceptance"),
            });

            StringAssert.Contains(
                "public static readonly ItemId ItemIdAcceptance = new(\"pet_vs_monster.item_id_acceptance\");",
                content);
        }

        [Test]
        public void WriteIfChanged_UnchangedOutput_ReturnsFalseAndPreservesTimestamp()
        {
            string path = Path.Combine(Path.GetTempPath(), "GameItemIds.g.cs");
            string content = ItemIdCodeGenerator.GenerateContent(new[]
            {
                Definition("pet_vs_monster.gem", "Gem"),
            });

            File.WriteAllText(path, content);
            DateTime timestamp = File.GetLastWriteTimeUtc(path);

            Assert.IsFalse(ItemIdCodeGenerator.WriteIfChanged(path, content));
            Assert.AreEqual(timestamp, File.GetLastWriteTimeUtc(path));

            File.Delete(path);
        }

        private static ItemDefinition Definition(string id, string codeName)
        {
            var definition = new ItemDefinition();
            SetField(definition, "id", ItemId.Parse(id));
            SetField(definition, "codeName", codeName);
            return definition;
        }

        private static void SetField(object target, string fieldName, object value)
        {
            FieldInfo field = target.GetType()
                .GetField(fieldName, BindingFlags.Instance | BindingFlags.NonPublic);

            Assert.IsNotNull(field, fieldName);
            field.SetValue(target, value);
        }
    }
}
